normalize:
  outputs:

    dev_with_fal:
      type: fal
      db_profile: dev # This points to your main adapter

    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5439
      user: admin
      pass: admin
      dbname: mydb
      schema: public

  #target: dev
  target: dev_with_fal