playground:
  outputs:

    dbt_fal:
      type: fal
      db_profile: prod # This points to your main adapter

    prod:
      type: postgres
      threads: 1
      host: localhost
      port: 5439
      user: admin
      pass: admin
      dbname: mydb
      schema: public

  #target: dev
  target: dbt_fal
